name: medication_reminder
description: A new Flutter project to remind users to take their medicine.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # Required for localization
  
  # Core packages for our app
  flutter_local_notifications: ^17.1.2 # For scheduling notifications
  sqflite: ^2.3.3+1 # For local database storage
  path_provider: ^2.1.3 # For finding the database path
  path: ^1.9.0
  fl_chart: ^0.68.0 # For charts and reports for the database
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  permission_handler: ^11.0.1 # For handling permissions
  flutter_native_timezone: ^2.0.0 # To detect device timezone

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true # Enables internationalization support
